# Generated by Django 4.1.2 on 2022-11-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Datas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("Email", models.CharField(default="", max_length=20)),
                ("phone", models.IntegerField(default="")),
                ("programs", models.CharField(default="", max_length=20)),
                ("Message", models.CharField(default="", max_length=100)),
            ],
        ),
    ]
